version: 2
updates:
  # Fetch and update latest `npm` packages
#   - package-ecosystem: npm
#     directory: '/'
#     schedule:
#       interval: monthly
#       time: '00:00'
#     open-pull-requests-limit: 10
#     reviewers:
#       - dvgamerr
#     assignees:
#       - dvgamerr
#     commit-message:
#       prefix: fix
#       prefix-development: chore
#       include: scope
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
