version: 2
jobs:
  build:
    environment:
      PROJECT: "website-profile"
      VERSION: "v3.0.1"
    working_directory: ~/app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-builder-{{ checksum "package.json" }}
          - v1-builder-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-builder-{{ checksum "package.json" }}
      - run: npm run eslint
      - run: npm run build
      - run: rm -Rf node_modules
      - restore_cache:
          keys:
          - v1-production-{{ checksum "package.json" }}
          - v1-production-
      - run: npm i --only=production
      - save_cache:
          paths:
            - node_modules
          key: v1-production-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER --password $DOCKER_PASS container.touno.io
      - run: docker build -t container.touno.io/$PROJECT:latest .
      - run: docker tag container.touno.io/$PROJECT:latest container.touno.io/$PROJECT:$VERSION 
      - run: docker push container.touno.io/$PROJECT