version: "3.8"
# https://github.com/docker/for-win/issues/5202#issuecomment-585498457

volumes:
  db-mongo:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/dvgamerr/docker/db-mongo'

services:
  db-mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2"
          memory: 2G
      placement:
        constraints:
          - node.role == manager
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Bangkok
    volumes:
      - db-mongo:/data/db
