name: pages-generate

on:
  push:
    branches: [  main ]
    tags:
      - v*

jobs:
  push:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout SourceCode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: SonarScanner Verify
      #   uses: docker://sonarsource/sonar-scanner-cli:latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn --production --frozen-lockfile
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
